version: "3.9"

services:
  auth-api:
    build: .
    container_name: auth-api
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@fastapi-db:5432/mydb"
      SECRET_KEY: "SHARED_SECRET_KEY_123"
      ALGORITHM: "HS256"
    networks:
      - jobscout_net

networks:
  jobscout_net:
    external: true