version: "3.9"

services:
  auth-api:
    build: .
    container_name: auth-api
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - JWT_SECRET_KEY=supersecretkey
      - JWT_ALGORITHM=HS256
    networks:
      - jobscout_net
    depends_on:
      - db

networks:
  jobscout_net:
    external: true